---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: raghuramdevopsengineer/node
          ports:
            - containerPort: 4000
          imagePullPolicy: Always  

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: raghuramdevopsengineer/react
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: node-conf
                  key: server-uri
              imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
